-- ==============================================================================
-- SI Sheet - Supabase Seed Data
-- Dataset: 52 Unique Problems, 53 Lab Assignments, 24 Topics, 9 Lab Dates
-- ==============================================================================

-- 1. Topics (24)
insert into public.topics (name, slug) values
  ('Arrays', 'arrays'),
  ('Backtracking', 'backtracking'),
  ('Binary Search', 'binary-search'),
  ('Bit Manipulation', 'bit-manipulation'),
  ('Data Structures', 'data-structures'),
  ('Dynamic Programming', 'dynamic-programming'),
  ('Game Theory', 'game-theory'),
  ('Greedy', 'greedy'),
  ('Hashing', 'hashing'),
  ('Linked List', 'linked-list'),
  ('Mathematical / Combinatorics', 'mathematical-combinatorics'),
  ('Monotonic Stack', 'monotonic-stack'),
  ('Number Theory', 'number-theory'),
  ('Prefix Sum', 'prefix-sum'),
  ('Prime / Sieve', 'prime-sieve'),
  ('Queue / Deque', 'queue-deque'),
  ('Recursion', 'recursion'),
  ('Sliding Window', 'sliding-window'),
  ('Stack', 'stack'),
  ('String Matching', 'string-matching'),
  ('Strings', 'strings'),
  ('Subarrays', 'subarrays'),
  ('Substrings', 'substrings'),
  ('Trie', 'trie')
on conflict (name) do nothing;

-- 2. Labs (9)
insert into public.labs (lab_date, title) values
  ('2026-08-03', 'Lab: 03 Aug 2026'),
  ('2026-08-04', 'Lab: 04 Aug 2026'),
  ('2026-08-11', 'Lab: 11 Aug 2026'),
  ('2026-08-17', 'Lab: 17 Aug 2026'),
  ('2026-08-24', 'Lab: 24 Aug 2026'),
  ('2026-08-25', 'Lab: 25 Aug 2026'),
  ('2026-09-01', 'Lab: 01 Sep 2026'),
  ('2026-09-02', 'Lab: 02 Sep 2026'),
  ('2026-09-21', 'Lab: 21 Sep 2026')
on conflict (lab_date) do nothing;

-- 3. Problems (52)
insert into public.problems (title, url, platform) values
  ('Triple Trouble', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/triple-trouble', 'Smart Interviews'),
  ('Repeated Numbers', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/repeated-numbers', 'Smart Interviews'),
  ('XOR of Sum of Pairs', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/xor-of-sum-of-pairs', 'Smart Interviews'),
  ('Sum of XOR of Pairs', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-xor-of-pairs', 'Smart Interviews'),
  ('Subset Sum', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/subset-sum', 'Smart Interviews'),
  ('Count Subset Sums Equals K', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/count-subset-sums-equals-k', 'Smart Interviews'),
  ('Count Total Set Bits', 'https://www.interviewbit.com/problems/count-total-set-bits/', 'InterviewBit'),
  ('Balanced Parentheses', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/balanced-parentheses', 'Smart Interviews'),
  ('Smart Square', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/smart-square', 'Smart Interviews'),
  ('String Partitioning', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/string-partitioning', 'Smart Interviews'),
  ('N-Queens', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/n-queens', 'Smart Interviews'),
  ('Interleavings', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/interleavings', 'Smart Interviews'),
  ('Cabinets Partitioning', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/cabinets-partitioning', 'Smart Interviews'),
  ('Protective Villagers', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/protective-villagers', 'Smart Interviews'),
  ('Enclosing Substring', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/enclosing-substring', 'Smart Interviews'),
  ('Sum of Subarrays', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-subarrays', 'Smart Interviews'),
  ('Query Odd Sum', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/query-odd-sum', 'Smart Interviews'),
  ('Words Start & End with Vowel', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/words-start-and-end-with-vowel', 'Smart Interviews'),
  ('Substring Matching', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/substring-matching', 'Smart Interviews'),
  ('Rabin Karp String Matching Algorithm', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/rabin-karp-string-matching-algorithm', 'Smart Interviews'),
  ('KMP String Matching Algorithm', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/kmp-string-matching-algorithm', 'Smart Interviews'),
  ('Longest Palindromic Substring Hard', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/longest-palindromic-substring-hard', 'Smart Interviews'),
  ('Prime Love', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/prime-love', 'Smart Interviews'),
  ('Two Primes', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/two-primes', 'Smart Interviews'),
  ('Check isPrime', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/check-isprime', 'Smart Interviews'),
  ('Large Range Primes', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/large-range-primes', 'Smart Interviews'),
  ('Prime Coins', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/prime-coins', 'Smart Interviews'),
  ('Optimal Prime Game', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/optimal-prime-game', 'Smart Interviews'),
  ('Greedy Prime Game', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/greedy-prime-game', 'Smart Interviews'),
  ('Mixed Prime Game', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/mixed-prime-game', 'Smart Interviews'),
  ('Alice and Bob Coin Game-1', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/alice-and-bob-coin-game-1', 'Smart Interviews'),
  ('Alice and Bob Coin Game-2', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/alice-and-bob-coin-game-2', 'Smart Interviews'),
  ('Game of Letters', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/game-of-letters', 'Smart Interviews'),
  ('Shifting Stones', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/shifting-stones', 'Smart Interviews'),
  ('Quadruples of XOR', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/quadruples-of-xor', 'Smart Interviews'),
  ('Subsequence Sum', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/subsequence-sum', 'Smart Interviews'),
  ('Equal 0s and 1s', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/equal-0s-and-1s', 'Smart Interviews'),
  ('Toggle 01', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/toggle-01', 'Smart Interviews'),
  ('First Missing Positive Integer', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/first-missing-positive-integer', 'Smart Interviews'),
  ('Sum of OR of Subarrays', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-or-of-subarrays', 'Smart Interviews'),
  ('Sum of AND of Subarrays', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-and-of-subarrays', 'Smart Interviews'),
  ('Next Greater Element I', 'https://leetcode.com/problems/next-greater-element-i/description/?envType=problem-list-v2&envId=monotonic-stack', 'LeetCode'),
  ('Daily Temperatures', 'https://leetcode.com/problems/daily-temperatures/description/?envType=problem-list-v2&envId=monotonic-stack', 'LeetCode'),
  ('Rectangular Area Under Histogram', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/rectangular-area-under-histogram', 'Smart Interviews'),
  ('Implement Deque', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/implement-deque', 'Smart Interviews'),
  ('Window Maximum', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/window-maximum', 'Smart Interviews'),
  ('Maximal Rectangle', 'https://leetcode.com/problems/maximal-rectangle/description/?envType=problem-list-v2&envId=monotonic-stack', 'LeetCode'),
  ('LRU Cache', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/lru-cache', 'Smart Interviews'),
  ('HackerRank — Pending Data Structures / Linked Lists', 'https://www.hackerrank.com/domains/data-structures?filters%5Bsubdomains%5D%5B%5D=linked-lists', 'HackerRank'),
  ('Copy List with Random Pointer', 'https://leetcode.com/problems/copy-list-with-random-pointer/description/', 'LeetCode'),
  ('Max Rhyming Word Length', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/max-rhyming-word-length', 'Smart Interviews'),
  ('Maximum XOR', 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/maximum-xor', 'Smart Interviews')
on conflict (url) do nothing;

-- 4. Problem Topics
insert into public.problem_topics (problem_id, topic_id)
select p.id, t.id from (
  values
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/triple-trouble', 'Bit Manipulation'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/triple-trouble', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/repeated-numbers', 'Bit Manipulation'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/repeated-numbers', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/xor-of-sum-of-pairs', 'Bit Manipulation'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/xor-of-sum-of-pairs', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-xor-of-pairs', 'Bit Manipulation'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-xor-of-pairs', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-xor-of-pairs', 'Prefix Sum'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/subset-sum', 'Recursion'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/subset-sum', 'Backtracking'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/subset-sum', 'Dynamic Programming'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/count-subset-sums-equals-k', 'Recursion'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/count-subset-sums-equals-k', 'Backtracking'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/count-subset-sums-equals-k', 'Dynamic Programming'),
    ('https://www.interviewbit.com/problems/count-total-set-bits/', 'Bit Manipulation'),
    ('https://www.interviewbit.com/problems/count-total-set-bits/', 'Mathematical / Combinatorics'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/balanced-parentheses', 'Recursion'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/balanced-parentheses', 'Backtracking'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/balanced-parentheses', 'Stack'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/smart-square', 'Recursion'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/smart-square', 'Backtracking'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/string-partitioning', 'Recursion'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/string-partitioning', 'Backtracking'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/string-partitioning', 'Strings'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/n-queens', 'Recursion'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/n-queens', 'Backtracking'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/interleavings', 'Recursion'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/interleavings', 'Strings'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/cabinets-partitioning', 'Binary Search'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/cabinets-partitioning', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/protective-villagers', 'Binary Search'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/protective-villagers', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/enclosing-substring', 'Binary Search'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/enclosing-substring', 'Sliding Window'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/enclosing-substring', 'Substrings'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-subarrays', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-subarrays', 'Subarrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-subarrays', 'Prefix Sum'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/query-odd-sum', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/query-odd-sum', 'Prefix Sum'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/words-start-and-end-with-vowel', 'Strings'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/words-start-and-end-with-vowel', 'Prefix Sum'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/substring-matching', 'Strings'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/substring-matching', 'String Matching'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/rabin-karp-string-matching-algorithm', 'Strings'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/rabin-karp-string-matching-algorithm', 'String Matching'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/rabin-karp-string-matching-algorithm', 'Hashing'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/kmp-string-matching-algorithm', 'Strings'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/kmp-string-matching-algorithm', 'String Matching'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/longest-palindromic-substring-hard', 'Strings'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/longest-palindromic-substring-hard', 'Substrings'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/longest-palindromic-substring-hard', 'Dynamic Programming'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/prime-love', 'Number Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/prime-love', 'Prime / Sieve'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/two-primes', 'Number Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/two-primes', 'Prime / Sieve'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/check-isprime', 'Number Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/check-isprime', 'Prime / Sieve'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/large-range-primes', 'Number Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/large-range-primes', 'Prime / Sieve'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/prime-coins', 'Game Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/prime-coins', 'Number Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/optimal-prime-game', 'Game Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/optimal-prime-game', 'Number Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/optimal-prime-game', 'Dynamic Programming'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/greedy-prime-game', 'Game Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/greedy-prime-game', 'Greedy'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/mixed-prime-game', 'Game Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/mixed-prime-game', 'Number Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/alice-and-bob-coin-game-1', 'Game Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/alice-and-bob-coin-game-2', 'Game Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/alice-and-bob-coin-game-2', 'Dynamic Programming'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/game-of-letters', 'Game Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/game-of-letters', 'Strings'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/shifting-stones', 'Game Theory'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/shifting-stones', 'Greedy'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/quadruples-of-xor', 'Bit Manipulation'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/quadruples-of-xor', 'Hashing'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/quadruples-of-xor', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/subsequence-sum', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/subsequence-sum', 'Dynamic Programming'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/subsequence-sum', 'Recursion'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/equal-0s-and-1s', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/equal-0s-and-1s', 'Prefix Sum'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/equal-0s-and-1s', 'Hashing'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/toggle-01', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/toggle-01', 'Bit Manipulation'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/toggle-01', 'Prefix Sum'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/first-missing-positive-integer', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/first-missing-positive-integer', 'Hashing'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-or-of-subarrays', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-or-of-subarrays', 'Bit Manipulation'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-or-of-subarrays', 'Subarrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-and-of-subarrays', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-and-of-subarrays', 'Bit Manipulation'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-and-of-subarrays', 'Subarrays'),
    ('https://leetcode.com/problems/next-greater-element-i/description/?envType=problem-list-v2&envId=monotonic-stack', 'Stack'),
    ('https://leetcode.com/problems/next-greater-element-i/description/?envType=problem-list-v2&envId=monotonic-stack', 'Monotonic Stack'),
    ('https://leetcode.com/problems/next-greater-element-i/description/?envType=problem-list-v2&envId=monotonic-stack', 'Arrays'),
    ('https://leetcode.com/problems/daily-temperatures/description/?envType=problem-list-v2&envId=monotonic-stack', 'Stack'),
    ('https://leetcode.com/problems/daily-temperatures/description/?envType=problem-list-v2&envId=monotonic-stack', 'Monotonic Stack'),
    ('https://leetcode.com/problems/daily-temperatures/description/?envType=problem-list-v2&envId=monotonic-stack', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/rectangular-area-under-histogram', 'Stack'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/rectangular-area-under-histogram', 'Monotonic Stack'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/rectangular-area-under-histogram', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/implement-deque', 'Queue / Deque'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/implement-deque', 'Data Structures'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/window-maximum', 'Queue / Deque'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/window-maximum', 'Sliding Window'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/window-maximum', 'Monotonic Stack'),
    ('https://leetcode.com/problems/maximal-rectangle/description/?envType=problem-list-v2&envId=monotonic-stack', 'Stack'),
    ('https://leetcode.com/problems/maximal-rectangle/description/?envType=problem-list-v2&envId=monotonic-stack', 'Monotonic Stack'),
    ('https://leetcode.com/problems/maximal-rectangle/description/?envType=problem-list-v2&envId=monotonic-stack', 'Dynamic Programming'),
    ('https://leetcode.com/problems/maximal-rectangle/description/?envType=problem-list-v2&envId=monotonic-stack', 'Arrays'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/lru-cache', 'Linked List'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/lru-cache', 'Hashing'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/lru-cache', 'Data Structures'),
    ('https://www.hackerrank.com/domains/data-structures?filters%5Bsubdomains%5D%5B%5D=linked-lists', 'Linked List'),
    ('https://www.hackerrank.com/domains/data-structures?filters%5Bsubdomains%5D%5B%5D=linked-lists', 'Data Structures'),
    ('https://leetcode.com/problems/copy-list-with-random-pointer/description/', 'Linked List'),
    ('https://leetcode.com/problems/copy-list-with-random-pointer/description/', 'Hashing'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/max-rhyming-word-length', 'Trie'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/max-rhyming-word-length', 'Strings'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/maximum-xor', 'Trie'),
    ('https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/maximum-xor', 'Bit Manipulation')
) as v(problem_url, topic_name)
join public.problems p on p.url = v.problem_url
join public.topics t on t.name = v.topic_name
on conflict do nothing;

-- 5. Lab Problems (53 Lab Assignments)
insert into public.lab_problems (lab_id, problem_id)
select l.id, p.id from (
  values
    ('2026-08-03'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/triple-trouble'),
    ('2026-08-03'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/repeated-numbers'),
    ('2026-08-03'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/xor-of-sum-of-pairs'),
    ('2026-08-03'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-xor-of-pairs'),
    ('2026-08-03'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/subset-sum'),
    ('2026-08-04'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/subset-sum'),
    ('2026-08-03'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/count-subset-sums-equals-k'),
    ('2026-08-03'::date, 'https://www.interviewbit.com/problems/count-total-set-bits/'),
    ('2026-08-04'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/balanced-parentheses'),
    ('2026-08-04'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/smart-square'),
    ('2026-08-04'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/string-partitioning'),
    ('2026-08-04'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/n-queens'),
    ('2026-08-04'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/interleavings'),
    ('2026-08-11'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/cabinets-partitioning'),
    ('2026-08-11'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/protective-villagers'),
    ('2026-08-11'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/enclosing-substring'),
    ('2026-08-17'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-subarrays'),
    ('2026-08-17'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/query-odd-sum'),
    ('2026-08-17'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/words-start-and-end-with-vowel'),
    ('2026-08-17'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/substring-matching'),
    ('2026-08-17'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/rabin-karp-string-matching-algorithm'),
    ('2026-08-17'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/kmp-string-matching-algorithm'),
    ('2026-08-17'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/longest-palindromic-substring-hard'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/prime-love'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/two-primes'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/check-isprime'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/large-range-primes'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/prime-coins'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/optimal-prime-game'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/greedy-prime-game'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/mixed-prime-game'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/alice-and-bob-coin-game-1'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/alice-and-bob-coin-game-2'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/game-of-letters'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/shifting-stones'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/quadruples-of-xor'),
    ('2026-08-24'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/subsequence-sum'),
    ('2026-08-25'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/equal-0s-and-1s'),
    ('2026-08-25'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/toggle-01'),
    ('2026-08-25'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/first-missing-positive-integer'),
    ('2026-08-25'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-or-of-subarrays'),
    ('2026-08-25'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/sum-of-and-of-subarrays'),
    ('2026-09-01'::date, 'https://leetcode.com/problems/next-greater-element-i/description/?envType=problem-list-v2&envId=monotonic-stack'),
    ('2026-09-01'::date, 'https://leetcode.com/problems/daily-temperatures/description/?envType=problem-list-v2&envId=monotonic-stack'),
    ('2026-09-01'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/rectangular-area-under-histogram'),
    ('2026-09-01'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/implement-deque'),
    ('2026-09-01'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/window-maximum'),
    ('2026-09-01'::date, 'https://leetcode.com/problems/maximal-rectangle/description/?envType=problem-list-v2&envId=monotonic-stack'),
    ('2026-09-02'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/lru-cache'),
    ('2026-09-02'::date, 'https://www.hackerrank.com/domains/data-structures?filters%5Bsubdomains%5D%5B%5D=linked-lists'),
    ('2026-09-02'::date, 'https://leetcode.com/problems/copy-list-with-random-pointer/description/'),
    ('2026-09-21'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/max-rhyming-word-length'),
    ('2026-09-21'::date, 'https://hive.smartinterviews.in/contests/smart-interviews-primary/problems/maximum-xor')
) as v(lab_date, problem_url)
join public.labs l on l.lab_date = v.lab_date
join public.problems p on p.url = v.problem_url
on conflict do nothing;
